[package]
name = "nft1_core"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
candid = "0.10.10"
serde = "1.0.204"
data-url = "0.3.1"
postcard = { version = "1.1.1", features = ["use-std"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
postcard-bindgen = "0.5.2"